#
# GitLab CI configuration.
#
# https://docs.gitlab.com/ee/ci/yaml
#

#
# Dispatch.
#
# This is to split 1 file with 𝐍 pipelines (complex) into 𝐍 files with 1 pipeline (simple).
#
# Rules are the dispatch values for methods (pipelines).
# A dispatch value defined in `workflow` should be associated with exactly 1 method in `include`.
#

# Dispatch values.
workflow:
  rules:
    # Merge request push.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
      auto_cancel:
        on_new_commit: interruptible
    # Default branch push.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
      auto_cancel:
        on_new_commit: none
    # Tag push.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null
      when: always
      auto_cancel:
        on_new_commit: none

# Methods.
#
# Note that methods should have their `workflow` defined with their dispatch values.
# Child methods should have their `workflow` defined in their own files.
include:
  # Merge request push.
  - local: .gitlab/pipelines/merge_request.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  # Default branch push.
  - local: .gitlab/pipelines/default_branch.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  # Tag push.
  - local: .gitlab/pipelines/tag.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null

#
# Jobs.
#

# GitLab complains about no jobs otherwise.
⛔️:
  stage: .pre
  rules:
    - when: never
  script:
    - exit 1
