apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.nodePlugin.driverName }}
  labels:
    {{- include "msfs-csi.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Ephemeral
    - Persistent
