package main

import (
	"path/filepath"
	"testing"
)

func TestManifestBootstrapEligibility(t *testing.T) {
	for _, testCase := range []struct {
		name         string
		readOnly     bool
		manifestPath string
		bootstrap    bool
		generate     bool
	}{
		{
			name:         "read-only with manifest bootstraps and may generate",
			readOnly:     true,
			manifestPath: "/var/lib/msfs/manifests/s3",
			bootstrap:    true,
			generate:     true,
		},
		{
			name:         "writable with manifest bootstraps but must not generate",
			readOnly:     false,
			manifestPath: "/var/lib/msfs/manifests/s3",
			bootstrap:    true,
			generate:     false,
		},
		{
			name:         "read-only without manifest does not bootstrap",
			readOnly:     true,
			manifestPath: "",
			bootstrap:    false,
			generate:     true,
		},
		{
			name:         "writable without manifest does not bootstrap",
			readOnly:     false,
			manifestPath: "",
			bootstrap:    false,
			generate:     false,
		},
	} {
		t.Run(testCase.name, func(t *testing.T) {
			backend := &backendStruct{
				dirName:      "s3",
				readOnly:     testCase.readOnly,
				manifestPath: testCase.manifestPath,
			}

			if got := manifestBootstrapEligible(backend); got != testCase.bootstrap {
				t.Errorf("manifestBootstrapEligible() = %v, want %v", got, testCase.bootstrap)
			}
			if got := manifestGenerationEligible(backend); got != testCase.generate {
				t.Errorf("manifestGenerationEligible() = %v, want %v", got, testCase.generate)
			}
		})
	}
}

// TestManifestBootstrapWritableBackendOverlaysDeltas covers the path a writable
// manifest-backed mount takes at bootstrap: the base manifest generated by an
// earlier session is read through the delta overlay, so entries created,
// updated, and deleted through the mount are reconstructed.
func TestManifestBootstrapWritableBackendOverlaysDeltas(t *testing.T) {
	tmpDir := t.TempDir()
	baseMTime := mustParseTime(t, "2026-01-01T00:00:00Z")

	backend := newMockBackend("test/", []mockObject{
		{key: "test/kept.bin", size: 100, eTag: "etag-kept", mTime: baseMTime},
		{key: "test/replaced.bin", size: 200, eTag: "etag-replaced", mTime: baseMTime},
		{key: "test/removed.bin", size: 300, eTag: "etag-removed", mTime: baseMTime},
	})
	backend.manifestPath = filepath.Join(tmpDir, "manifest")
	backend.readOnly = false

	if !manifestBootstrapEligible(backend) {
		t.Fatalf("writable backend with a manifest path must be bootstrap-eligible")
	}
	if manifestGenerationEligible(backend) {
		t.Fatalf("writable backend must not generate its manifest at mount")
	}

	err := generateManifest(&manifestGenConfig{
		workers:     2,
		outputPath:  backend.manifestPath,
		backendName: backend.dirName,
		backend:     backend,
	})
	if err != nil {
		t.Fatalf("generateManifest: %v", err)
	}

	writeMTime := mustParseTime(t, "2026-02-02T00:00:00Z")
	deltas := []struct {
		op    string
		entry manifestDirEntry
	}{
		{op: manifestDeltaUpsert, entry: manifestDirEntry{Kind: "f", Basename: "created.bin", Size: 400, ETag: "etag-created", MTime: writeMTime}},
		{op: manifestDeltaUpsert, entry: manifestDirEntry{Kind: "f", Basename: "replaced.bin", Size: 500, ETag: "etag-replaced-v2", MTime: writeMTime}},
		{op: manifestDeltaDelete, entry: manifestDirEntry{Kind: "f", Basename: "removed.bin", MTime: writeMTime}},
	}
	for _, delta := range deltas {
		entry := delta.entry
		if err := appendManifestDeltaRecord(backend.manifestPath, "", delta.op, &entry); err != nil {
			t.Fatalf("appendManifestDeltaRecord(%s, %s): %v", delta.op, entry.Basename, err)
		}
	}

	entries, err := readManifestPartWithDelta(backend.manifestPath, "")
	if err != nil {
		t.Fatalf("readManifestPartWithDelta: %v", err)
	}

	byName := make(map[string]manifestDirEntry, len(entries))
	for _, entry := range entries {
		byName[entry.Basename] = entry
	}

	if _, found := byName["removed.bin"]; found {
		t.Errorf("removed.bin should be hidden by its tombstone")
	}

	created, found := byName["created.bin"]
	if !found {
		t.Fatalf("created.bin should be reconstructed from the delta log")
	}
	if created.Size != 400 || created.ETag != "etag-created" || !created.MTime.Equal(writeMTime) {
		t.Errorf("created.bin = %+v, want size 400 / etag-created / %v", created, writeMTime)
	}

	replaced, found := byName["replaced.bin"]
	if !found {
		t.Fatalf("replaced.bin missing from overlay result")
	}
	if replaced.Size != 500 || replaced.ETag != "etag-replaced-v2" {
		t.Errorf("replaced.bin = %+v, want the delta record to supersede the base entry", replaced)
	}

	kept, found := byName["kept.bin"]
	if !found {
		t.Fatalf("kept.bin missing from overlay result")
	}
	if kept.Size != 100 || kept.ETag != "etag-kept" {
		t.Errorf("kept.bin = %+v, want the untouched base entry", kept)
	}

	if len(entries) != 3 {
		t.Errorf("expected 3 entries (kept, replaced, created), got %d: %+v", len(entries), entries)
	}
}

// TestManifestBootstrapSkipsDeltaDirectory confirms the reserved delta area is
// not mistaken for a base manifest part during ingest enumeration.
func TestManifestBootstrapSkipsDeltaDirectory(t *testing.T) {
	tmpDir := t.TempDir()
	manifestDir := filepath.Join(tmpDir, "manifest")

	entry := manifestDirEntry{
		Kind:     "f",
		Basename: "only-in-delta.bin",
		Size:     10,
		ETag:     "etag-delta",
		MTime:    mustParseTime(t, "2026-03-03T00:00:00Z"),
	}
	if err := appendManifestDeltaRecord(manifestDir, "", manifestDeltaUpsert, &entry); err != nil {
		t.Fatalf("appendManifestDeltaRecord: %v", err)
	}

	deltaPath := manifestDeltaPath(manifestDir)
	if filepath.Base(filepath.Dir(deltaPath)) != manifestDeltaDirName {
		t.Errorf("delta log must live under %q, got %q", manifestDeltaDirName, deltaPath)
	}

	// No base part exists for the root, so the overlay result is delta-only.
	entries, err := readManifestPartWithDelta(manifestDir, "")
	if err != nil {
		t.Fatalf("readManifestPartWithDelta: %v", err)
	}
	if len(entries) != 1 || entries[0].Basename != "only-in-delta.bin" {
		t.Fatalf("expected the delta-only entry, got %+v", entries)
	}
}
