[test-azure-uswest-rclone]
type = azureblob
endpoint = https://nvdataplatformdev.blob.core.windows.net
base_path = msc-test
workload_identity_tenant_id = 43083d15-7273-40c1-b7db-39efd9ccc17a
workload_identity_client_id = dea5cb00-7993-49ca-81f1-1e1c660a7764

[test-oci-rclone]
type = oracleobjectstorage
namespace = axvrabcwoa8f
base_path = msc-test

[test-s3-iad-rclone]
type = s3
region = us-east-1
endpoint = https://s3.us-east-1.amazonaws.com
base_path = msc-integration-test-0001
profile_name = aws

[test-s3e-rclone]
type = s3
region = us-east-1
base_path = msc-integration-test-0001--use1-az4--x-s3
profile_name = aws

[test-s3-iad-base-path-with-prefix-rclone]
type = s3
region = us-east-1
endpoint = https://s3.us-east-1.amazonaws.com
base_path = msc-integration-test-0001/test-data
profile_name = aws

[test-swift-pdx-rclone]
type = s8k
region = us-east-1
endpoint = https://pdx.s8k.io
base_path = msc-integration-test-0001
profile_name = s8k

[test-swift-pdx-base-path-with-prefix-rclone]
type = s8k
region = us-east-1
endpoint = https://pdx.s8k.io
base_path = msc-integration-test-0001/test-data
profile_name = s8k
