#
# GitLab CI configuration.
#
# https://docs.gitlab.com/ee/ci/yaml
#

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

stages:
  - Pipeline

default:
  # This is a very minimal Linux with just Nix. It's not NixOS.
  image: nixos/nix:latest

variables:
  # So we don't have to do `nix --experimental-features "nix-command flakes"` every time.
  #
  # https://nixos.org/manual/nix/stable/command-ref/env-common#env-NIX_CONFIG
  NIX_CONFIG: |
    experimental-features = nix-command flakes

#
# Jobs.
#

# Properties we can't set with `default`.
.default:
  stage: Pipeline
  environment:
    name: Beta
    action: access

Run E2E Tests:
  extends:
    - .default
  parallel:
    matrix:
      - PYTHON_BINARY:
          - python3.10
          - python3.11
          - python3.12
          - python3.13
  script:
    - |
      nix develop '.#"'${PYTHON_BINARY}'"' --command bash -c "
        export OCI_CONFIG_FILE=${OCI_CLIENT_CONFIGURATION_BETA} &&
        export MSC_CONFIG=${MULTI_STORAGE_CLIENT_CONFIGURATION_BETA} &&
        export GOOGLE_APPLICATION_CREDENTIALS=${GCS_APPLICATION_DEFAULT_CREDENTIALS_BETA} &&
        cp ${MULTI_STORAGE_CLIENT_RCLONE_CONF_BETA} "~/.rclone.conf" &&
        just python-binary=${PYTHON_BINARY} run-e2e-tests
      "
  artifacts:
    reports:
      junit: .reports/e2e/pytest.xml
