#
# GitLab CI configuration.
#
# https://docs.gitlab.com/ee/ci/yaml
#

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

stages:
  - 💿

default:
  # Using this instead of nixos/nix:latest to handle hardcoded dynamic linker paths.
  image: debian:unstable-slim
  before_script:
    # Install Nix with the Determinate Nix Installer. The `nix` command and flakes are enabled by default.
    #
    # https://github.com/DeterminateSystems/nix-installer#in-a-container
    - apt update -y
    - apt install curl git -y
    - curl --fail --location https://install.determinate.systems/nix --proto '=https' --show-error --silent --tlsv1.2 | sh -s -- install linux --extra-conf "sandbox = false" --init none --no-confirm
    - . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
    # Create `nix.conf` + `.netrc` files and alias Git URLs.
    #
    # https://nix.dev/manual/nix/latest/command-ref/conf-file
    # https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file
    # https://git-scm.com/docs/git-config
    - mkdir --parents /etc/nix
    - |
      tee --append /etc/nix/nix.conf << END_OF_FILE
      access-tokens = ${CI_SERVER_HOST}=PAT:${CI_JOB_TOKEN}
      netrc-file = /etc/nix/.netrc
      END_OF_FILE
    - |
      tee --append /etc/nix/.netrc << END_OF_FILE
      machine ${CI_SERVER_HOST}
      login gitlab-ci-token
      password ${CI_JOB_TOKEN}
      END_OF_FILE
    - git config set --system --append url."${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_FQDN}".insteadOf "${CI_SERVER_URL}"
    - git config set --system --append url."${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_FQDN}".insteadOf "ssh://git@${CI_SERVER_SHELL_SSH_HOST}:${CI_SERVER_SHELL_SSH_PORT}"
  interruptible: true

#
# Jobs.
#

# Properties we can't set with `default`.
.default:
  stage: 💿

Build:
  extends:
    - .default
  parallel:
    matrix:
      - PYTHON_BINARY:
          - python3.10
          - python3.11
          - python3.12
          - python3.13
  script:
    - |
      nix develop '.#"'${PYTHON_BINARY}'"' --command bash -c "
        just python-binary=${PYTHON_BINARY} build &&
        just python-binary=${PYTHON_BINARY} run-minimal-verification
      "
  artifacts:
    paths:
      - .reports/unit/coverage/
      - dist/
      - docs/dist/
    reports:
      codequality: .reports/ruff.json
      coverage_report:
        coverage_format: cobertura
        path: .reports/unit/coverage.xml
      junit: .reports/unit/pytest.xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
