#
# GitLab CI configuration.
#
# https://docs.gitlab.com/ee/ci/yaml
#

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"

stages:
  - Pipeline

default:
  # This is a very minimal Linux with just Nix. It's not NixOS.
  image: nixos/nix:latest
  interruptible: true

variables:
  # So we don't have to do `nix --experimental-features "nix-command flakes"` every time.
  #
  # https://nixos.org/manual/nix/stable/command-ref/env-common#env-NIX_CONFIG
  NIX_CONFIG: |
    experimental-features = nix-command flakes

#
# Jobs.
#

# Properties we can't set with `default`.
.default:
  stage: Pipeline

Build:
  extends:
    - .default
  parallel:
    matrix:
      - PYTHON_BINARY:
          - python3.9
          - python3.10
          - python3.11
          - python3.12
          - python3.13
  script:
    - |
      nix develop '.#"'${PYTHON_BINARY}'"' --command bash -c "
        just python-binary=${PYTHON_BINARY} build &&
        just python-binary=${PYTHON_BINARY} run-minimal-verification
      "
  artifacts:
    paths:
      - .reports/unit/coverage/
      - dist/
      - docs/dist/
    reports:
      codequality: .reports/ruff.json
      coverage_report:
        coverage_format: cobertura
        path: .reports/unit/coverage.xml
      junit: .reports/unit/pytest.xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
