#
# GitLab CI configuration.
#
# https://docs.gitlab.com/ee/ci/yaml
#

stages:
  - 💽

default:
  interruptible: true

#
# Jobs.
#

# Properties we can't set with `default`.
.default:
  stage: 💽

.child:
  extends:
    - .default
  trigger:
    forward:
      pipeline_variables: false
      yaml_variables: false
    # TODO: Switch to `mirror` once on GitLab 18.2.
    strategy: depend

Source:
  extends:
    - .child
  trigger:
    include: .gitlab/pipelines/.source.yml

Beta:
  extends:
    - .child
  needs:
    - Source
  rules:
    - when: manual
      allow_failure: true
  environment:
    name: Beta
    action: start
  trigger:
    include: .gitlab/pipelines/.beta.yml
