#
# GitLab CI configuration.
#
# https://docs.gitlab.com/ee/ci/yaml
#

stages:
  - Pipeline

default:
  # This is a very minimal Linux with just Nix. It's not NixOS.
  image: nixos/nix:latest

variables:
  # So we don't have to do `nix --experimental-features "nix-command flakes"` every time.
  #
  # https://nixos.org/manual/nix/stable/command-ref/env-common#env-NIX_CONFIG
  NIX_CONFIG: |
    experimental-features = nix-command flakes

#
# Jobs.
#

# Properties we can't set with `default`.
.default:
  stage: Pipeline

Source:
  extends:
    - .default
  trigger:
    include: .gitlab/pipelines/.source.yml
    strategy: depend
  interruptible: true

Beta:
  extends:
    - .default
  needs:
    - Source
  rules:
    # Default branch push.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG == null && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # Tag push.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null
  resource_group: Beta
  environment:
    name: Beta
    action: start
  trigger:
    include: .gitlab/pipelines/.beta.yml
    strategy: depend

Production:
  extends:
    - .default
  needs:
    - Beta
  rules:
    # Tag push.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG != null
  resource_group: Production
  environment:
    name: Production
    action: start
  trigger:
    include: .gitlab/pipelines/.production.yml
    strategy: depend
