#
# GitLab CI configuration.
#
# https://docs.gitlab.com/ee/ci/yaml
#

stages:
  - 💽

default:
  interruptible: false

#
# Jobs.
#

# Properties we can't set with `default`.
.default:
  stage: 💽

.child:
  extends:
    - .default
  trigger:
    forward:
      pipeline_variables: false
      yaml_variables: false
    # TODO: Switch to `mirror` once on GitLab 18.2.
    strategy: depend

PyPI:
  extends:
    - .child
  resource_group: PyPI
  environment:
    name: PyPI
    action: start
  trigger:
    include: .gitlab/pipelines/.pypi.yml
