#
# GitLab CI configuration.
#
# https://docs.gitlab.com/ee/ci/yaml
#

stages:
  - 💿

default:
  tags:
    - cd-r.platform.hardware/x86-64.12
    - cd-r.platform.supervisor/linux.sysbox-runc.docker-engine
  # This is a very minimal Linux with just Nix. It's not NixOS.
  image: nixos/nix:latest
  before_script:
    # Create `nix.conf` + `.netrc` files and alias Git URLs.
    #
    # https://nix.dev/manual/nix/latest/command-ref/conf-file
    # https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file
    # https://git-scm.com/docs/git-config
    - mkdir --parents /etc/nix
    # `experimental-features` can be omitted if Nix was installed with the Determinate Nix Installer (e.g. when using other base images).
    - |
      tee --append /etc/nix/nix.conf << END_OF_FILE
      experimental-features = nix-command flakes
      access-tokens = ${CI_SERVER_HOST}=PAT:${CI_JOB_TOKEN}
      netrc-file = /etc/nix/.netrc
      END_OF_FILE
    - |
      tee --append /etc/nix/.netrc << END_OF_FILE
      machine ${CI_SERVER_HOST}
      login gitlab-ci-token
      password ${CI_JOB_TOKEN}
      END_OF_FILE
    - git config set --system --append url."${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_FQDN}".insteadOf "${CI_SERVER_URL}"
    - git config set --system --append url."${CI_SERVER_PROTOCOL}://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_FQDN}".insteadOf "ssh://git@${CI_SERVER_SHELL_SSH_HOST}:${CI_SERVER_SHELL_SSH_PORT}"

#
# Jobs.
#

# Properties we can't set with `default`.
.default:
  stage: 💿

Update Dependencies:
  extends:
    - .default
  script:
    - |
      nix develop --command bash -c "
        echo 'TODO: Add Renovate to auto-update dependencies and .licenses.'
      "
