#
# GitHub Actions workflow configuration.
#
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
#

name: Beta
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
defaults:
  run:
    shell: nix develop --command bash -e {0}
jobs:
  run-e2e-tests:
    name: Run E2E Tests
    environment:
      name: Beta
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        python-binary:
          - python3.10
          - python3.11
          - python3.12
          - python3.13
      fail-fast: false
    runs-on: linux-amd64-cpu16
    defaults:
      run:
        shell: nix develop ${{ github.workspace }}#"\"${{ matrix.python-binary }}\"" --command bash -e {0}
    steps:
      # Checkout.
      - uses: actions/checkout@v6
      # Install Nix.
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          summarize: false
      # Main.
      - working-directory: multi-storage-client
        run: |
          just python-binary=${{ matrix.python-binary }} run-e2e-tests
