#
# GitHub Actions workflow configuration.
#
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
#

name: Beta
on:
  workflow_call:
defaults:
  run:
    shell: nix develop --command bash -e {0}
jobs:
  run-e2e-tests:
    name: Run E2E Tests
    environment:
      name: Beta
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        python-binary:
          - python3.10
          - python3.11
          - python3.12
          - python3.13
      fail-fast: false
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop ${{ github.workspace }}#"\"${{ matrix.python-binary }}\"" --command bash -e {0}
    steps:
      # Checkout.
      - uses: actions/checkout@v6
      # Install Nix + Magic Nix Cache.
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          summarize: false
      - uses: DeterminateSystems/magic-nix-cache-action@main
      # Install uv + enable uv caching.
      #
      # The Nix shell provides uv so this is only for uv caching.
      - uses: astral-sh/setup-uv@v8.0.0
        env:
          UV_NO_MODIFY_PATH: true
        with:
          cache-suffix: multi-storage-client
          enable-cache: true
      # Main.
      - working-directory: multi-storage-client
        run: |
          just python-binary=${{ matrix.python-binary }} run-e2e-tests
