#
# GitHub Actions workflow configuration.
#
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
#

name: Production
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
defaults:
  run:
    shell: nix develop --command bash -e {0}
jobs:
  publish-release:
    name: Publish Release
    environment:
      name: Production
    permissions:
      contents: write
    runs-on: linux-amd64-cpu16
    steps:
      # Checkout.
      - uses: actions/checkout@v6
      # Install Nix.
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          summarize: false
      # Main.
      #
      # Assumes the Source child workflow ran before in the same parent workflow.
      #
      # All `actions/upload-artifact` paths must include a `-` path to preserve workspace structure.
      #
      # https://github.com/actions/upload-artifact/issues/174
      - uses: actions/download-artifact@v8
        with:
          merge-multiple: true
      # TODO: Switch to `--phase publish` once everything else is in place.
      - working-directory: multi-storage-client-scripts
        run: |
          uv run msc-scripts publish-release --github-token ${{ secrets.GITHUB_TOKEN }} --phase check
