#
# GitHub Actions workflow configuration.
#
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
#

name: Default Branch
on:
  push:
    branches:
      - main
jobs:
  source:
    name: Source
    permissions:
      contents: read
    uses: ./.github/workflows/.source.yml
  beta:
    name: Beta
    needs:
      - source
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/.beta.yml
  production:
    name: Production
    needs:
      - beta
    permissions:
      contents: write
    uses: ./.github/workflows/.production.yml
