#
# GitHub Actions workflow configuration.
#
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
#

name: Supply
on:
  # Add more events to mirror the GitLab pipeline if development moves to GitHub.
  push:
    tags:
      - '*'
jobs:
  production:
    name: Production
    # Tag push.
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    concurrency:
      group: Production
    uses: ./.github/workflows/.production.yml
